spring:
  cloud:
    gateway:
      httpclient:
        # 全局的TCP连接超时时间默认时间是45秒，网络故障的时候，连接时间要等待45秒，而网络连接是同步阻塞
        connect-timeout: 2000
        # 全局的响应超时时间，网络链接后，后端服务多久不返回网关就报错 The response timeout.
        response-timeout: PT30S
        pool:
          # scg的空闲连接超时回收时间
          max-idle-time: PT1S
        websocket:
          # 1024*1024*10  上传的文件大小
          max-frame-payload-length: 10485760
            # 全局跨域配置
            #globalcors:
            #cors-configurations:
            #'[/**]': #匹配所有请求
            #allowedOrigins: "*" #跨域处理 允许所有的域
            #allowedMethods: # 支持的方法
            #- GET
            #- POST
            #- PUT
          #- DELETE
      # nacos 服务发现
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
        # 配置全局路由
        #default-filters:
        # 开发环境重写路由规则 该配置会影响到灰度组件，如果开启需要关闭灰度组件
        #- DevLocalRewriteRouteFilter=true
        # 签名校验
        #- SecretGatewayFilter=true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000